---
- name: stop monit
  service:
    name: monit
    state: stopped
  become: yes
  become_user: root

- name: start monit
  service:
    name: monit
    state: started
  become: yes
  become_user: root

- name: restart monit
  service:
    name: monit
    state: restarted
  become: yes
  become_user: root
